import { MeetingNoticeTypeEnum } from "@sparcs-clubs/web/features/meeting/components/MeetingNoticeItem";

const mockUpMeetingNotice = {
  items: [
    {
      id: 1,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제11차 운영위원회 (8월, 임시회)",
      date: new Date("2024-07-22"),
    },
    {
      id: 2,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제4차 확대운영위원회 (7월, 임시회)",
      date: new Date("2024-07-20"),
    },
    {
      id: 3,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "6월 분과회의 기간 공고",
      date: new Date("2024-06-15"),
    },
    {
      id: 4,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "6월 분과회의 안건지",
      date: new Date("2024-06-20"),
    },
    {
      id: 5,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 밴드음악분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 6,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 생활체육분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 7,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 연행예술분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 8,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-24"),
    },
    {
      id: 9,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-28"),
    },
    {
      id: 10,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-30"),
    },
    {
      id: 11,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "(For Everyone) 2024년 제1차 전체동아리대표자회의 (3월, 정기회)",
      date: new Date("2024-03-13"),
    },
    {
      id: 12,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "(For Everyone) 2024년 제1차 전체동아리대표자회의 (3월, 정기회)",
      date: new Date("2024-03-18"),
    },
    {
      id: 13,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-24"),
    },
    {
      id: 14,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-28"),
    },
    {
      id: 15,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-30"),
    },
    {
      id: 16,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "(For Everyone) 2024년 제1차 전체동아리대표자회의 (3월, 정기회)",
      date: new Date("2024-03-13"),
    },
    {
      id: 17,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "(For Everyone) 2024년 제1차 전체동아리대표자회의 (3월, 정기회)",
      date: new Date("2024-03-18"),
    },
    {
      id: 18,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제11차 운영위원회 (8월, 임시회)",
      date: new Date("2024-07-22"),
    },
    {
      id: 19,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제4차 확대운영위원회 (7월, 임시회)",
      date: new Date("2024-07-20"),
    },
    {
      id: 20,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "6월 분과회의 기간 공고",
      date: new Date("2024-06-15"),
    },
    {
      id: 21,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "6월 분과회의 안건지",
      date: new Date("2024-06-20"),
    },
    {
      id: 22,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 밴드음악분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 23,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 생활체육분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 24,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 연행예술분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 25,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제11차 운영위원회 (8월, 임시회)",
      date: new Date("2024-07-22"),
    },
    {
      id: 26,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제4차 확대운영위원회 (7월, 임시회)",
      date: new Date("2024-07-20"),
    },
    {
      id: 27,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "6월 분과회의 기간 공고",
      date: new Date("2024-06-15"),
    },
    {
      id: 28,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "6월 분과회의 안건지",
      date: new Date("2024-06-20"),
    },
    {
      id: 29,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 밴드음악분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 30,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 생활체육분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 31,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 연행예술분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 32,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-24"),
    },
    {
      id: 33,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-28"),
    },
    {
      id: 34,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-30"),
    },
    {
      id: 35,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "(For Everyone) 2024년 제1차 전체동아리대표자회의 (3월, 정기회)",
      date: new Date("2024-03-13"),
    },
    {
      id: 36,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "(For Everyone) 2024년 제1차 전체동아리대표자회의 (3월, 정기회)",
      date: new Date("2024-03-18"),
    },
    {
      id: 37,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-24"),
    },
    {
      id: 38,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-28"),
    },
    {
      id: 39,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-30"),
    },
    {
      id: 40,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "(For Everyone) 2024년 제1차 전체동아리대표자회의 (3월, 정기회)",
      date: new Date("2024-03-13"),
    },
    {
      id: 41,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "(For Everyone) 2024년 제1차 전체동아리대표자회의 (3월, 정기회)",
      date: new Date("2024-03-18"),
    },
    {
      id: 42,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제11차 운영위원회 (8월, 임시회)",
      date: new Date("2024-07-22"),
    },
    {
      id: 43,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제4차 확대운영위원회 (7월, 임시회)",
      date: new Date("2024-07-20"),
    },
    {
      id: 44,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "6월 분과회의 기간 공고",
      date: new Date("2024-06-15"),
    },
    {
      id: 45,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "6월 분과회의 안건지",
      date: new Date("2024-06-20"),
    },
    {
      id: 46,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 밴드음악분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 47,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 생활체육분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 48,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 연행예술분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 49,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제11차 운영위원회 (8월, 임시회)",
      date: new Date("2024-07-22"),
    },
    {
      id: 50,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제4차 확대운영위원회 (7월, 임시회)",
      date: new Date("2024-07-20"),
    },
    {
      id: 51,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "6월 분과회의 기간 공고",
      date: new Date("2024-06-15"),
    },
    {
      id: 52,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "6월 분과회의 안건지",
      date: new Date("2024-06-20"),
    },
    {
      id: 53,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 밴드음악분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 54,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 생활체육분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 55,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 연행예술분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 56,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-24"),
    },
    {
      id: 57,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-28"),
    },
    {
      id: 58,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-30"),
    },
    {
      id: 59,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "(For Everyone) 2024년 제1차 전체동아리대표자회의 (3월, 정기회)",
      date: new Date("2024-03-13"),
    },
    {
      id: 60,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "(For Everyone) 2024년 제1차 전체동아리대표자회의 (3월, 정기회)",
      date: new Date("2024-03-18"),
    },
    {
      id: 61,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-24"),
    },
    {
      id: 62,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-28"),
    },
    {
      id: 63,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-30"),
    },
    {
      id: 64,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "(For Everyone) 2024년 제1차 전체동아리대표자회의 (3월, 정기회)",
      date: new Date("2024-03-13"),
    },
    {
      id: 65,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "(For Everyone) 2024년 제1차 전체동아리대표자회의 (3월, 정기회)",
      date: new Date("2024-03-18"),
    },
    {
      id: 66,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제11차 운영위원회 (8월, 임시회)",
      date: new Date("2024-07-22"),
    },
    {
      id: 67,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제4차 확대운영위원회 (7월, 임시회)",
      date: new Date("2024-07-20"),
    },
    {
      id: 68,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "6월 분과회의 기간 공고",
      date: new Date("2024-06-15"),
    },
    {
      id: 69,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "6월 분과회의 안건지",
      date: new Date("2024-06-20"),
    },
    {
      id: 70,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 밴드음악분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 71,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 생활체육분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 72,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 연행예술분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 73,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제11차 운영위원회 (8월, 임시회)",
      date: new Date("2024-07-22"),
    },
    {
      id: 74,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제4차 확대운영위원회 (7월, 임시회)",
      date: new Date("2024-07-20"),
    },
    {
      id: 75,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "6월 분과회의 기간 공고",
      date: new Date("2024-06-15"),
    },
    {
      id: 76,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "6월 분과회의 안건지",
      date: new Date("2024-06-20"),
    },
    {
      id: 77,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 밴드음악분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 78,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 생활체육분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 79,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 연행예술분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 80,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-24"),
    },
    {
      id: 81,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-28"),
    },
    {
      id: 82,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-30"),
    },
    {
      id: 83,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "(For Everyone) 2024년 제1차 전체동아리대표자회의 (3월, 정기회)",
      date: new Date("2024-03-13"),
    },
    {
      id: 84,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "(For Everyone) 2024년 제1차 전체동아리대표자회의 (3월, 정기회)",
      date: new Date("2024-03-18"),
    },
    {
      id: 85,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-24"),
    },
    {
      id: 86,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-28"),
    },
    {
      id: 87,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-30"),
    },
    {
      id: 88,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "(For Everyone) 2024년 제1차 전체동아리대표자회의 (3월, 정기회)",
      date: new Date("2024-03-13"),
    },
    {
      id: 89,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "(For Everyone) 2024년 제1차 전체동아리대표자회의 (3월, 정기회)",
      date: new Date("2024-03-18"),
    },
    {
      id: 90,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제11차 운영위원회 (8월, 임시회)",
      date: new Date("2024-07-22"),
    },
    {
      id: 91,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제4차 확대운영위원회 (7월, 임시회)",
      date: new Date("2024-07-20"),
    },
    {
      id: 92,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "6월 분과회의 기간 공고",
      date: new Date("2024-06-15"),
    },
    {
      id: 93,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "6월 분과회의 안건지",
      date: new Date("2024-06-20"),
    },
    {
      id: 94,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 밴드음악분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 95,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 생활체육분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 96,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 연행예술분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 97,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 연행예술분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 98,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제11차 운영위원회 (8월, 임시회)",
      date: new Date("2024-07-22"),
    },
    {
      id: 99,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제4차 확대운영위원회 (7월, 임시회)",
      date: new Date("2024-07-20"),
    },
    {
      id: 100,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "6월 분과회의 기간 공고",
      date: new Date("2024-06-15"),
    },
    {
      id: 101,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "6월 분과회의 안건지",
      date: new Date("2024-06-20"),
    },
    {
      id: 102,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 밴드음악분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 103,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 생활체육분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 104,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 연행예술분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 105,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-24"),
    },
    {
      id: 106,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-28"),
    },
    {
      id: 107,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-30"),
    },
    {
      id: 108,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "(For Everyone) 2024년 제1차 전체동아리대표자회의 (3월, 정기회)",
      date: new Date("2024-03-13"),
    },
    {
      id: 109,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "(For Everyone) 2024년 제1차 전체동아리대표자회의 (3월, 정기회)",
      date: new Date("2024-03-18"),
    },
    {
      id: 110,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-24"),
    },
    {
      id: 111,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-28"),
    },
    {
      id: 112,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "2024년 제3차 확대운영위원회 (5월, 정기회)",
      date: new Date("2024-05-30"),
    },
    {
      id: 113,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "(For Everyone) 2024년 제1차 전체동아리대표자회의 (3월, 정기회)",
      date: new Date("2024-03-13"),
    },
    {
      id: 114,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "(For Everyone) 2024년 제1차 전체동아리대표자회의 (3월, 정기회)",
      date: new Date("2024-03-18"),
    },
    {
      id: 115,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제11차 운영위원회 (8월, 임시회)",
      date: new Date("2024-07-22"),
    },
    {
      id: 116,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "2024년 제4차 확대운영위원회 (7월, 임시회)",
      date: new Date("2024-07-20"),
    },
    {
      id: 117,
      tag: MeetingNoticeTypeEnum.Notice,
      title: "6월 분과회의 기간 공고",
      date: new Date("2024-06-15"),
    },
    {
      id: 118,
      tag: MeetingNoticeTypeEnum.Agenda,
      title: "6월 분과회의 안건지",
      date: new Date("2024-06-20"),
    },
    {
      id: 119,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 밴드음악분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
    {
      id: 120,
      tag: MeetingNoticeTypeEnum.Meeting,
      title: "6월 생활체육분과 정기회의 회의록",
      date: new Date("2024-06-23"),
    },
  ],
  total: 120,
  offset: 12,
};

export default mockUpMeetingNotice;
