import { RentalOrderStatusEnum } from "@sparcs-clubs/interface/common/enum/rental.enum";

const mockupMyExeRnt = {
  items: [
    {
      id: 1,
      studentName: "술박스",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "전동 드릴 세트",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Applied,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 2,
      studentName: "술박스",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "전동 드릴 세트",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Applied,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 3,
      studentName: "술박스",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "전동 드릴 세트",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Applied,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 4,
      studentName: "술박스",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "돗자리",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Rejected,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 5,
      studentName: "술박스",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "돗자리",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Approved,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 6,
      studentName: "술박스",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "돗자리",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Approved,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 7,
      studentName: "술박스",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "돗자리",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Approved,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 8,
      studentName: "술박스",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "돗자리",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Rented,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 9,
      studentName: "술박스",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "돗자리",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Returned,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 10,
      studentName: "술박스",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "돗자리",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Overdue,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 11,
      studentName: "술박스2",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "전동 드릴 세트",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Applied,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 12,
      studentName: "술박스2",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "전동 드릴 세트",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Applied,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 13,
      studentName: "술박스2",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "전동 드릴 세트",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Applied,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 14,
      studentName: "술박스2",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "돗자리",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Rejected,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 15,
      studentName: "술박스2",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "돗자리",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Approved,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 16,
      studentName: "술박스2",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "돗자리",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Approved,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 17,
      studentName: "술박스2",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "돗자리",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Approved,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 18,
      studentName: "술박스2",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "돗자리",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Rented,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 19,
      studentName: "술박스2",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "돗자리",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Returned,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 20,
      studentName: "술박스3",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "돗자리",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Overdue,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 21,
      studentName: "술박스3",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "전동 드릴 세트",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Applied,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 22,
      studentName: "술박스3",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "전동 드릴 세트",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Applied,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 23,
      studentName: "술박스3",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "전동 드릴 세트",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Applied,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 24,
      studentName: "술박스3",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "돗자리",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Rejected,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 25,
      studentName: "술박스3",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "돗자리",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Approved,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 26,
      studentName: "술박스3",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "돗자리",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Approved,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 27,
      studentName: "술박스3",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "돗자리",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Approved,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 28,
      studentName: "술박스3",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "돗자리",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Rented,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 29,
      studentName: "술박스3",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "돗자리",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Returned,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
    {
      id: 30,
      studentName: "술박스3",
      applicantName: "이지윤",
      phoneNumber: "010-9612-4975",
      objects: [
        {
          id: 1,
          name: "돗자리",
          number: 3,
        },
        {
          id: 2,
          name: "드릴",
          number: 1,
        },
        {
          id: 3,
          name: "어쩌구",
          number: 1,
        },
      ],
      statusEnum: RentalOrderStatusEnum.Returned,
      desiredStart: new Date("2024-03-11"),
      desiredEnd: new Date("2024-03-18"),
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
    },
  ],
  total: 30,
  offset: 30,
};

export default mockupMyExeRnt;
