import type { ClubInfo } from "@sparcs-clubs/web/types/clubs.types";
import { fromObj } from "@sparcs-clubs/web/types/clubs.types";

// mockup model to interface
const mockupData = [
  {
    division: 1,
    name: "생활문화",
    clubs: [
      {
        id: 1,
        clubName: "궁극의 맛",
        clubType: "정동아리",
        characteristicKr: "요리",
        clubPresident: "장주원",
        advisor: null,
        totalMembers: 1,
      },
      {
        id: 2,
        clubName: "샹그릴라",
        clubType: "정동아리",
        characteristicKr: "애니메이션 감상 및 서브컬쳐",
        clubPresident: "김경민",
        advisor: null,
        totalMembers: 58,
      },
      {
        id: 3,
        clubName: "여로",
        clubType: "정동아리",
        characteristicKr: "여행",
        clubPresident: "강현성",
        advisor: "김유식",
        totalMembers: 31,
      },
      {
        id: 4,
        clubName: "예쁜영화",
        clubType: "정동아리",
        characteristicKr: "영화감상",
        clubPresident: "정재민",
        advisor: "정재승",
        totalMembers: 32,
      },
      {
        id: 5,
        clubName: "칼디",
        clubType: "정동아리",
        characteristicKr: "커피&바리스타",
        clubPresident: "최원준",
        advisor: "오혜연",
        totalMembers: 8,
      },
      {
        id: 6,
        clubName: "판놀음",
        clubType: "정동아리",
        characteristicKr: "보드 게임",
        clubPresident: "양동연",
        advisor: "김혜진",
        totalMembers: 32,
      },
      {
        id: 7,
        clubName: "Khartes",
        clubType: "정동아리",
        characteristicKr: "트레이딩 카드 게임",
        clubPresident: "양진혁",
        advisor: null,
        totalMembers: 23,
      },
      {
        id: 8,
        clubName: "OPTeamus",
        clubType: "정동아리",
        characteristicKr: "이스포츠",
        clubPresident: "신승빈",
        advisor: "박병호",
        totalMembers: 3,
      },
      {
        id: 9,
        clubName: "THE MIXER",
        clubType: "정동아리",
        characteristicKr: "칵테일",
        clubPresident: "구도훈",
        advisor: null,
        totalMembers: 22,
      },
      {
        id: 75,
        clubName: "패플리",
        clubType: "정동아리",
        characteristicKr: "패션",
        clubPresident: "탁한진",
        advisor: null,
        totalMembers: 12,
      },
      {
        id: 76,
        clubName: "Boardom",
        clubType: "정동아리",
        characteristicKr: "보드게임",
        clubPresident: "Munim Hasan Wasi",
        advisor: "Insik Shin",
        totalMembers: 1,
      },
      {
        id: 77,
        clubName: "Moonshine",
        clubType: "가동아리",
        characteristicKr: "양조",
        clubPresident: "임채민",
        advisor: null,
        totalMembers: 13,
      },
      {
        id: 89,
        clubName: "KASTLE",
        clubType: "가동아리",
        characteristicKr: "체스",
        clubPresident: "Jaden Jorradol",
        advisor: null,
        totalMembers: 1,
      },
      {
        id: 92,
        clubName: "카이시엘",
        clubType: "가동아리",
        characteristicKr:
          "제과제빵 활동을 통해 학우들의 다양한 문화활동을 장려함.",
        clubPresident: "김나연",
        advisor: null,
        totalMembers: 36,
      },
      {
        id: 104,
        clubName: "COKAIN",
        clubType: "가동아리",
        characteristicKr: "코스프레",
        clubPresident: "김강민",
        advisor: null,
        totalMembers: 1,
      },
      {
        id: 106,
        clubName: "모닥불",
        clubType: "가동아리",
        characteristicKr: "캠핑",
        clubPresident: "김지하",
        advisor: null,
        totalMembers: 1,
      },
      {
        id: 107,
        clubName: "카슐랭",
        clubType: "가동아리",
        characteristicKr: "맛집탐방",
        clubPresident: "이정민",
        advisor: null,
        totalMembers: 1,
      },
      {
        id: 110,
        clubName: "웅(熊)",
        clubType: "가동아리",
        characteristicKr: "고기굽기에 대한 연구",
        clubPresident: "이서윤",
        advisor: null,
        totalMembers: 1,
      },
    ],
  },
  {
    division: 2,
    name: "연행예술",
    clubs: [
      {
        id: 10,
        clubName: "이박터",
        clubType: "정동아리",
        characteristicKr: "연극",
        clubPresident: "허수영",
        advisor: null,
        totalMembers: 18,
      },
      {
        id: 11,
        clubName: "일루젼 카이스트",
        clubType: "정동아리",
        characteristicKr: "힙합, 스트릿 및 K-POP댄스",
        clubPresident: "정민혁",
        advisor: "김현정",
        totalMembers: 17,
      },
      {
        id: 12,
        clubName: "Lunatic",
        clubType: "정동아리",
        characteristicKr: "스트릿 댄스",
        clubPresident: "박선우",
        advisor: "민범기",
        totalMembers: 36,
      },
      {
        id: 13,
        clubName: "MindFreak",
        clubType: "정동아리",
        characteristicKr: "마술 및 타로",
        clubPresident: "이창섭",
        advisor: null,
        totalMembers: 19,
      },
      {
        id: 14,
        clubName: "Number",
        clubType: "정동아리",
        characteristicKr: "뮤지컬",
        clubPresident: "김동현",
        advisor: "이경면",
        totalMembers: 20,
      },
    ],
  },
  {
    division: 3,
    name: "전시창작",
    clubs: [
      {
        id: 15,
        clubName: "곰발바닥",
        clubType: "정동아리",
        characteristicKr: "수공예",
        clubPresident: "김채현",
        advisor: "이지윤",
        totalMembers: 37,
      },
      {
        id: 16,
        clubName: "그리미주아",
        clubType: "정동아리",
        characteristicKr: "순수미술",
        clubPresident: "예건희",
        advisor: "조현정",
        totalMembers: 27,
      },
      {
        id: 17,
        clubName: "문학의 뜨락",
        clubType: "정동아리",
        characteristicKr: "문예창작 및 합평",
        clubPresident: "신승운",
        advisor: "전봉관",
        totalMembers: 1,
      },
      {
        id: 18,
        clubName: "별바라기",
        clubType: "정동아리",
        characteristicKr: "별 관측 및 사진 촬영, 사진 전시회 운영과 외부 출사",
        clubPresident: "오윤종",
        advisor: "최한림",
        totalMembers: 38,
      },
      {
        id: 19,
        clubName: "빛따라",
        clubType: "정동아리",
        characteristicKr: "사진",
        clubPresident: "김휘용",
        advisor: "김민혁",
        totalMembers: 3,
      },
      {
        id: 20,
        clubName: "열정부",
        clubType: "정동아리",
        characteristicKr:
          "만화창작 및 디지털 일러스트레이션 및 애니메이션 제작",
        clubPresident: "서해린",
        advisor: null,
        totalMembers: 11,
      },
      {
        id: 21,
        clubName: "은막",
        clubType: "정동아리",
        characteristicKr: "독립영화 제작",
        clubPresident: "김나희",
        advisor: "전봉관",
        totalMembers: 23,
      },
      {
        id: 91,
        clubName: "KAIST Chronicles",
        clubType: "가동아리",
        characteristicKr: "영문",
        clubPresident: "김동은",
        advisor: null,
        totalMembers: 1,
      },
      {
        id: 95,
        clubName: "위로자전거",
        clubType: "가동아리",
        characteristicKr: "새활용",
        clubPresident: "방민솔",
        advisor: null,
        totalMembers: 1,
      },
      {
        id: 98,
        clubName: "LEtsGO",
        clubType: "가동아리",
        characteristicKr: "일반 레고 및 나노블럭 조립 후 전시활동",
        clubPresident: "김진현",
        advisor: null,
        totalMembers: 9,
      },
    ],
  },
  {
    division: 4,
    name: "밴드음악",
    clubs: [
      {
        id: 22,
        clubName: "강적",
        clubType: "정동아리",
        characteristicKr: "하드 락 밴드",
        clubPresident: "조한빈",
        advisor: "이탁연",
        totalMembers: 11,
      },
      {
        id: 23,
        clubName: "동틀무렵",
        clubType: "정동아리",
        characteristicKr: "모던락 밴드",
        clubPresident: "이해인",
        advisor: "이경면",
        totalMembers: 29,
      },
      {
        id: 24,
        clubName: "인피니트",
        clubType: "정동아리",
        characteristicKr: "메탈 및 얼터너티브 메탈 관련 밴드음악",
        clubPresident: "김준호",
        advisor: "윤효상",
        totalMembers: 18,
      },
      {
        id: 25,
        clubName: "창작동화",
        clubType: "정동아리",
        characteristicKr: "재즈 및 창작곡 공연",
        clubPresident: "최홍일",
        advisor: "배석형",
        totalMembers: 13,
      },
      {
        id: 26,
        clubName: "CarpeDiem",
        clubType: "정동아리",
        characteristicKr: "팝 밴드",
        clubPresident: "김예찬",
        advisor: "조항정",
        totalMembers: 1,
      },
      {
        id: 27,
        clubName: "Praiser",
        clubType: "정동아리",
        characteristicKr: "KAIST 내 크리스천들을 위한 CCM을 연주하는 밴드",
        clubPresident: "박동민",
        advisor: "성영철",
        totalMembers: 11,
      },
      {
        id: 28,
        clubName: "STURGEON",
        clubType: "정동아리",
        characteristicKr: "EMO/CORE/PUNK 장르의 밴드음악 합주 및 공연",
        clubPresident: "김예린",
        advisor: null,
        totalMembers: 14,
      },
      {
        id: 29,
        clubName: "Twenties Dream",
        clubType: "정동아리",
        characteristicKr: "펑크락 밴드",
        clubPresident: "조원준",
        advisor: "이동만",
        totalMembers: 14,
      },
      {
        id: 111,
        clubName: "Shift",
        clubType: "가동아리",
        characteristicKr: "International Rock Band",
        clubPresident: "Nurlybay Akmerey",
        advisor: null,
        totalMembers: 8,
      },
    ],
  },
  {
    division: 5,
    name: "보컬음악",
    clubs: [
      {
        id: 30,
        clubName: "구토스",
        clubType: "정동아리",
        characteristicKr: "힙합, R&B",
        clubPresident: "신동환",
        advisor: "권경하",
        totalMembers: 21,
      },
      {
        id: 31,
        clubName: "여섯줄",
        clubType: "정동아리",
        characteristicKr: "어쿠스틱 보컬",
        clubPresident: "이유섭",
        advisor: null,
        totalMembers: 5,
      },
      {
        id: 32,
        clubName: "HUG",
        clubType: "정동아리",
        characteristicKr: "버스킹 및 실용음악",
        clubPresident: "김시은",
        advisor: "류석영",
        totalMembers: 1,
      },
      {
        id: 33,
        clubName: "KAIST CHORUS",
        clubType: "정동아리",
        characteristicKr: "합창 및 아카펠라",
        clubPresident: "성민석",
        advisor: "권세진",
        totalMembers: 12,
      },
      {
        id: 34,
        clubName: "MUSE",
        clubType: "정동아리",
        characteristicKr: "밴드세션&코러스",
        clubPresident: "정민호",
        advisor: "이해신",
        totalMembers: 22,
      },
    ],
  },
  {
    division: 6,
    name: "연주음악",
    clubs: [
      {
        id: 35,
        clubName: "소리모음",
        clubType: "정동아리",
        characteristicKr: "사물놀이 및 풍물",
        clubPresident: "김수진",
        advisor: null,
        totalMembers: 1,
      },
      {
        id: 36,
        clubName: "FingS",
        clubType: "정동아리",
        characteristicKr: "핑거스타일 기타",
        clubPresident: "유기민",
        advisor: "이승희",
        totalMembers: 26,
      },
      {
        id: 37,
        clubName: "LP",
        clubType: "정동아리",
        characteristicKr: "작곡",
        clubPresident: "윤남석",
        advisor: null,
        totalMembers: 26,
      },
      {
        id: 38,
        clubName: "PIAST",
        clubType: "정동아리",
        characteristicKr: "피아노 연주",
        clubPresident: "주선우",
        advisor: "최형순",
        totalMembers: 44,
      },
      {
        id: 80,
        clubName: "FUZE",
        clubType: "정동아리",
        characteristicKr: "디제잉 및 파티플래닝",
        clubPresident: "김현규",
        advisor: "남주한",
        totalMembers: 1,
      },
    ],
  },
  {
    division: 7,
    name: "사회",
    clubs: [
      {
        id: 39,
        clubName: "디딤돌",
        clubType: "정동아리",
        characteristicKr: "교육봉사 및 장애인 보조",
        clubPresident: "허지운",
        advisor: "정연식",
        totalMembers: 1,
      },
      {
        id: 40,
        clubName: "EWB-KAIST",
        clubType: "정동아리",
        characteristicKr: "적정 기술 개발 및 보급",
        clubPresident: "김수민",
        advisor: "배상민",
        totalMembers: 12,
      },
      {
        id: 41,
        clubName: "K-Let",
        clubType: "정동아리",
        characteristicKr: "청소년 대상 강연 및 멘토링",
        clubPresident: "고채현",
        advisor: "송지은",
        totalMembers: 6,
      },
      {
        id: 42,
        clubName: "KAINATION",
        clubType: "정동아리",
        characteristicKr: "기부",
        clubPresident: "강현우",
        advisor: "신병하",
        totalMembers: 5,
      },
      {
        id: 43,
        clubName: "SEED KAIST",
        clubType: "정동아리",
        characteristicKr: "과학 분야 교육봉사",
        clubPresident: "김준성",
        advisor: "신하용",
        totalMembers: 24,
      },
      {
        id: 44,
        clubName: "Silver Lining",
        clubType: "정동아리",
        characteristicKr: "봉사",
        clubPresident: "임지민",
        advisor: "이재우",
        totalMembers: 22,
      },
      {
        id: 94,
        clubName: "KAIST-SAE",
        clubType: "가동아리",
        characteristicKr: "지역사회 봉사 및 환경 보호",
        clubPresident: "권효진",
        advisor: null,
        totalMembers: 1,
      },
    ],
  },
  {
    division: 8,
    name: "종교",
    clubs: [
      {
        id: 45,
        clubName: "네비게이토",
        clubType: "정동아리",
        characteristicKr: "크리스천 리더십",
        clubPresident: "김예찬",
        advisor: "심기동",
        totalMembers: 12,
      },
      {
        id: 46,
        clubName: "사나래",
        clubType: "정동아리",
        characteristicKr: "가톨릭(천주교)",
        clubPresident: "정서경",
        advisor: "서민교",
        totalMembers: 16,
      },
      {
        id: 47,
        clubName: "CCC",
        clubType: "정동아리",
        characteristicKr: "대학생 기독교 선교",
        clubPresident: "황은빈",
        advisor: "김상규",
        totalMembers: 15,
      },
      {
        id: 48,
        clubName: "IVF",
        clubType: "정동아리",
        characteristicKr: "성경연구, 공동체 활동",
        clubPresident: "김재용",
        advisor: "한명준",
        totalMembers: 12,
      },
    ],
  },
  {
    division: 9,
    name: "구기체육",
    clubs: [
      {
        id: 49,
        clubName: "루키",
        clubType: "정동아리",
        characteristicKr: "야구",
        clubPresident: "박정원",
        advisor: "서민교",
        totalMembers: 22,
      },
      {
        id: 50,
        clubName: "아퀼라",
        clubType: "정동아리",
        characteristicKr: "풋살",
        clubPresident: "김도윤",
        advisor: "강준혁",
        totalMembers: 15,
      },
      {
        id: 51,
        clubName: "카이큐",
        clubType: "정동아리",
        characteristicKr: "배구",
        clubPresident: "이서준",
        advisor: "장무석",
        totalMembers: 8,
      },
      {
        id: 52,
        clubName: "투 (TU)",
        clubType: "정동아리",
        characteristicKr: "농구",
        clubPresident: "이승헌",
        advisor: "김석희",
        totalMembers: 1,
      },
      {
        id: 53,
        clubName: "허리케인",
        clubType: "정동아리",
        characteristicKr: "축구",
        clubPresident: "이서진",
        advisor: "강명수",
        totalMembers: 1,
      },
      {
        id: 54,
        clubName: "DOOLLY",
        clubType: "정동아리",
        characteristicKr: "5 대 5 정통 농구",
        clubPresident: "김주형",
        advisor: "최양규",
        totalMembers: 43,
      },
      {
        id: 55,
        clubName: "EDGE",
        clubType: "정동아리",
        characteristicKr: "탁구",
        clubPresident: "정유찬",
        advisor: "강준혁",
        totalMembers: 27,
      },
      {
        id: 56,
        clubName: "K-Bird",
        clubType: "정동아리",
        characteristicKr: "배드민턴",
        clubPresident: "박시우",
        advisor: null,
        totalMembers: 18,
      },
      {
        id: 57,
        clubName: "STROKE",
        clubType: "정동아리",
        characteristicKr: "테니스",
        clubPresident: "김지환",
        advisor: "오왕열",
        totalMembers: 1,
      },
      {
        id: 81,
        clubName: "스페어",
        clubType: "정동아리",
        characteristicKr: "볼링",
        clubPresident: "서민준",
        advisor: "한동훈",
        totalMembers: 18,
      },
      {
        id: 82,
        clubName: "UM",
        clubType: "가동아리",
        characteristicKr: "족구",
        clubPresident: "안제휘",
        advisor: null,
        totalMembers: 3,
      },
      {
        id: 93,
        clubName: "매버릭스",
        clubType: "가동아리",
        characteristicKr: "미식축구",
        clubPresident: "장준영",
        advisor: null,
        totalMembers: 1,
      },
      {
        id: 101,
        clubName: "고래당",
        clubType: "가동아리",
        characteristicKr: "구(4구, 8볼)",
        clubPresident: "장원혁",
        advisor: null,
        totalMembers: 1,
      },
      {
        id: 108,
        clubName: "PUD",
        clubType: "가동아리",
        characteristicKr: "캐주얼 배드민턴",
        clubPresident: "Calvin Samuel",
        advisor: null,
        totalMembers: 12,
      },
    ],
  },
  {
    division: 10,
    name: "생활체육",
    clubs: [
      {
        id: 58,
        clubName: "검우회",
        clubType: "정동아리",
        characteristicKr: "대한검도",
        clubPresident: "심한보",
        advisor: "김영진",
        totalMembers: 40,
      },
      {
        id: 59,
        clubName: "울랄라",
        clubType: "정동아리",
        characteristicKr: "스포츠 클라이밍",
        clubPresident: "김율",
        advisor: "이승욱",
        totalMembers: 32,
      },
      {
        id: 60,
        clubName: "카이스트 수영팀 가오리",
        clubType: "정동아리",
        characteristicKr: "경영(競泳) 및 핀수영",
        clubPresident: "김나령",
        advisor: "박수경",
        totalMembers: 8,
      },
      {
        id: 61,
        clubName: "KAKI",
        clubType: "정동아리",
        characteristicKr: "스노우보드 및 익스트림 스포츠",
        clubPresident: "신승헌",
        advisor: "배중면",
        totalMembers: 1,
      },
      {
        id: 83,
        clubName: "감성",
        clubType: "정동아리",
        characteristicKr: "자전거 라이딩",
        clubPresident: "김문수",
        advisor: null,
        totalMembers: 26,
      },
      {
        id: 85,
        clubName: "주짓스님",
        clubType: "정동아리",
        characteristicKr: "주짓수, MMA, 킥복싱",
        clubPresident: "노영래",
        advisor: null,
        totalMembers: 15,
      },
      {
        id: 90,
        clubName: "KAIST Winner Wrestling",
        clubType: "가동아리",
        characteristicKr: "레슬링",
        clubPresident: "김영진",
        advisor: null,
        totalMembers: 1,
      },
      {
        id: 96,
        clubName: "ASCEND",
        clubType: "가동아리",
        characteristicKr: "국제 종합운동 동아리",
        clubPresident: "김근형",
        advisor: null,
        totalMembers: 1,
      },
      {
        id: 103,
        clubName: "쨉쨉원투",
        clubType: "가동아리",
        characteristicKr: "복싱",
        clubPresident: "임수연",
        advisor: null,
        totalMembers: 7,
      },
      {
        id: 105,
        clubName: "북극곰",
        clubType: "가동아리",
        characteristicKr: "유도",
        clubPresident: "김창헌",
        advisor: null,
        totalMembers: 14,
      },
    ],
  },
  {
    division: 11,
    name: "이공학술",
    clubs: [
      {
        id: 62,
        clubName: "숲",
        clubType: "정동아리",
        characteristicKr: "생물의 관찰 및 탐구",
        clubPresident: "신동엽",
        advisor: "김상규",
        totalMembers: 21,
      },
      {
        id: 63,
        clubName: "질주",
        clubType: "정동아리",
        characteristicKr: "모터스포츠",
        clubPresident: "이관형",
        advisor: "김경수",
        totalMembers: 16,
      },
      {
        id: 64,
        clubName: "하제",
        clubType: "정동아리",
        characteristicKr: "게임 연구 및 제작",
        clubPresident: "김경완",
        advisor: "송준화",
        totalMembers: 1,
      },
      {
        id: 65,
        clubName: "GoN",
        clubType: "정동아리",
        characteristicKr: "정보보안 및 해킹",
        clubPresident: "조정훈",
        advisor: "차상길",
        totalMembers: 35,
      },
      {
        id: 66,
        clubName: "KAIST 수학문제연구회",
        clubType: "정동아리",
        characteristicKr: "수학",
        clubPresident: "이준혁",
        advisor: "엄상일",
        totalMembers: 58,
      },
      {
        id: 67,
        clubName: "KAIST Puple",
        clubType: "정동아리",
        characteristicKr: "퍼즐 연구 및 공유",
        clubPresident: "황윤찬",
        advisor: "안정연",
        totalMembers: 1,
      },
      {
        id: 68,
        clubName: "MR",
        clubType: "정동아리",
        characteristicKr: "로봇 연구 및 제작, 메이커 활동",
        clubPresident: "임준범",
        advisor: "박용화",
        totalMembers: 9,
      },
      {
        id: 69,
        clubName: "RUN",
        clubType: "정동아리",
        characteristicKr: "알고리즘 문제 해결",
        clubPresident: "이예린",
        advisor: "류석영",
        totalMembers: 16,
      },
      {
        id: 70,
        clubName: "Vlab",
        clubType: "정동아리",
        characteristicKr: "과학퀴즈와 인공지능",
        clubPresident: "이서현",
        advisor: "강민석",
        totalMembers: 12,
      },
      {
        id: 86,
        clubName: "Include",
        clubType: "가동아리",
        characteristicKr: "AI 학술",
        clubPresident: "김중현",
        advisor: null,
        totalMembers: 22,
      },
      {
        id: 100,
        clubName: "GDSC",
        clubType: "가동아리",
        characteristicKr: "KAIST 개발자 네트워킹 및 개발 관련 행사 주최",
        clubPresident: "윤지훈",
        advisor: null,
        totalMembers: 2,
      },
      {
        id: 102,
        clubName: "우주벌레",
        clubType: "가동아리",
        characteristicKr: "우주생물학 탐구 및 외계지적생명체 탐사",
        clubPresident: "이진우",
        advisor: null,
        totalMembers: 1,
      },
      {
        id: 109,
        clubName: "NUPS(NUPzuki Search club)",
        clubType: "가동아리",
        characteristicKr:
          "외계행성 관측 및 관측 기술 개발과 새로운 행성 발견, 외계생명체 거주 가능성 조사",
        clubPresident: "유동호",
        advisor: "김준한",
        totalMembers: 1,
      },
    ],
  },
  {
    division: 12,
    name: "인문학술",
    clubs: [
      {
        id: 71,
        clubName: "Freethinkers KAIST",
        clubType: "정동아리",
        characteristicKr: "자유사상",
        clubPresident: "이윤섭",
        advisor: "Grant Fisher",
        totalMembers: 14,
      },
      {
        id: 72,
        clubName: "ICISTS",
        clubType: "정동아리",
        characteristicKr: "학술행사 개최",
        clubPresident: "김지환",
        advisor: "조항정",
        totalMembers: 16,
      },
      {
        id: 73,
        clubName: "KFAC",
        clubType: "정동아리",
        characteristicKr: "금융 학술 동아리",
        clubPresident: "김희상",
        advisor: "최호용",
        totalMembers: 1,
      },
      {
        id: 74,
        clubName: "MSK",
        clubType: "정동아리",
        characteristicKr: "경영전략",
        clubPresident: "조은현",
        advisor: "김원준",
        totalMembers: 1,
      },
      {
        id: 87,
        clubName: "KAIST 법학회 Lawgical",
        clubType: "정동아리",
        characteristicKr: "법학",
        clubPresident: "김경래",
        advisor: "전우정",
        totalMembers: 15,
      },
      {
        id: 99,
        clubName: "KAIST LOOKIE",
        clubType: "가동아리",
        characteristicKr: "사회 문제 소셜 임팩트 창출, 소셜 벤처 창업 동아리",
        clubPresident: "양준원",
        advisor: null,
        totalMembers: 9,
      },
    ],
  },
];

const mockupClubDivisions = new Map<string, Array<ClubInfo>>();
mockupData.forEach(mockupClubDivision => {
  const tempMockupClubDivision: Array<ClubInfo> =
    mockupClubDivision.clubs.map(fromObj);
  tempMockupClubDivision.sort(
    (a, b) => a.type - b.type || a.name.localeCompare(b.name),
  );
  mockupClubDivisions.set(mockupClubDivision.name, tempMockupClubDivision);
});

// ----

export default mockupClubDivisions;
